"""empty message

Revision ID: 29a3ef971b50
Revises: b5c5240fb52c
Create Date: 2024-02-29 17:28:59.669991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a3ef971b50'
down_revision = 'b5c5240fb52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_group', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Dataset', ['dataset_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
