"""empty message

Revision ID: 528f32cee078
Revises: a268a42a22de
Create Date: 2024-02-29 03:42:30.594473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '528f32cee078'
down_revision = 'a268a42a22de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Account', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('admin', 'member', name='role'),
               type_=sa.Numeric(precision=1),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Account', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Numeric(precision=1),
               type_=postgresql.ENUM('admin', 'member', name='role'),
               existing_nullable=True)

    # ### end Alembic commands ###
