"""empty message

Revision ID: 79fd02cf9e0d
Revises: c45cd04799aa
Create Date: 2024-02-29 19:46:36.044516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79fd02cf9e0d'
down_revision = 'c45cd04799aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Acc_Group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid', sa.Boolean(), nullable=True))

    with op.batch_alter_table('Dataset_Group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Dataset_Group', schema=None) as batch_op:
        batch_op.drop_column('valid')

    with op.batch_alter_table('Acc_Group', schema=None) as batch_op:
        batch_op.drop_column('valid')

    # ### end Alembic commands ###
