"""empty message

Revision ID: 80de5581b32a
Revises: f69cbf163cc2
Create Date: 2024-02-29 11:29:41.351986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80de5581b32a'
down_revision = 'f69cbf163cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Archive', schema=None) as batch_op:
        batch_op.drop_index('ix_Archive_archive_name')
        batch_op.create_index(batch_op.f('ix_Archive_archive_name'), ['archive_name'], unique=False)

    with op.batch_alter_table('Dataset', schema=None) as batch_op:
        batch_op.drop_index('ix_Dataset_dataset_name')
        batch_op.create_index(batch_op.f('ix_Dataset_dataset_name'), ['dataset_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Dataset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Dataset_dataset_name'))
        batch_op.create_index('ix_Dataset_dataset_name', ['dataset_name'], unique=True)

    with op.batch_alter_table('Archive', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Archive_archive_name'))
        batch_op.create_index('ix_Archive_archive_name', ['archive_name'], unique=True)

    # ### end Alembic commands ###
