"""Update schema with correct column types

Revision ID: 86d9ffaecf67
Revises: 
Create Date: 2025-05-28 15:39:23.134272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d9ffaecf67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Patient', schema=None) as batch_op:
        batch_op.alter_column('patient_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('patient_birthdate',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=64),
               existing_nullable=True)

    with op.batch_alter_table('Series', schema=None) as batch_op:
        batch_op.alter_column('series_date',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=True)
        batch_op.alter_column('series_time',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('modality',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('station_name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('series_description',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('body_part_examined',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('sequence_name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('protocol_name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    with op.batch_alter_table('Study', schema=None) as batch_op:
        batch_op.alter_column('study_date',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=True)
        batch_op.alter_column('study_time',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('study_description',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('requested_procedure_description',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('institution_name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('requesting_physician',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('referring_physician_name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Study', schema=None) as batch_op:
        batch_op.alter_column('referring_physician_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('requesting_physician',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('institution_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('requested_procedure_description',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('study_description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('study_time',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
        batch_op.alter_column('study_date',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    with op.batch_alter_table('Series', schema=None) as batch_op:
        batch_op.alter_column('protocol_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('sequence_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('body_part_examined',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
        batch_op.alter_column('series_description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('station_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('manufacturer',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('modality',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
        batch_op.alter_column('series_time',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
        batch_op.alter_column('series_date',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    with op.batch_alter_table('Patient', schema=None) as batch_op:
        batch_op.alter_column('patient_birthdate',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('patient_name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
