"""empty message

Revision ID: 8eb98de59e6e
Revises: 29a3ef971b50
Create Date: 2024-02-29 17:59:59.462361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb98de59e6e'
down_revision = '29a3ef971b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Group', schema=None) as batch_op:
        batch_op.drop_index('ix_Group_group_name')
        batch_op.create_index(batch_op.f('ix_Group_group_name'), ['group_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Group_group_name'))
        batch_op.create_index('ix_Group_group_name', ['group_name'], unique=True)

    # ### end Alembic commands ###
