"""empty message

Revision ID: a268a42a22de
Revises: 8d6434b439ee
Create Date: 2024-02-29 02:57:58.394109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a268a42a22de'
down_revision = '8d6434b439ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('Dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archive_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Archive', ['archive_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Dataset', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('archive_id')

    with op.batch_alter_table('Account', schema=None) as batch_op:
        batch_op.drop_column('expiration_time')

    # ### end Alembic commands ###
