"""empty message

Revision ID: b5c5240fb52c
Revises: 9ac5d5eb16ea
Create Date: 2024-02-29 17:13:44.045004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c5240fb52c'
down_revision = '9ac5d5eb16ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Account', ['owner'], ['id'])

    with op.batch_alter_table('dataset_group', schema=None) as batch_op:
        batch_op.drop_column('owner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('Dataset', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
