"""Initial migration

Revision ID: c3e6b0587850
Revises: 
Create Date: 2024-09-23 19:18:19.593386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e6b0587850'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # 禁用所有约束
    op.execute("SET CONSTRAINTS ALL DEFERRED")

    # 添加新列
    with op.batch_alter_table("Patient", schema=None) as batch_op:
        batch_op.add_column(sa.Column("patient_weight", sa.Integer(), nullable=True))

    # 清理不一致的数据
    op.execute(
        """
        DELETE FROM "Dataset_Series"
        WHERE series_orthanc_id NOT IN (SELECT series_orthanc_id FROM "Series")
        OR study_orthanc_id NOT IN (SELECT study_orthanc_id FROM "Study")
    """
    )
    op.execute(
        """
        DELETE FROM "Dataset_Studies"
        WHERE study_orthanc_id NOT IN (SELECT study_orthanc_id FROM "Study")
    """
    )

    # 删除现有的外键约束（如果存在）
    op.drop_constraint(
        "Dataset_Series_series_orthanc_id_fkey", "Dataset_Series", type_="foreignkey"
    )
    op.drop_constraint(
        "Dataset_Series_study_orthanc_id_fkey", "Dataset_Series", type_="foreignkey"
    )
    op.drop_constraint(
        "Dataset_Studies_study_orthanc_id_fkey", "Dataset_Studies", type_="foreignkey"
    )

    # 创建新的外键约束
    with op.batch_alter_table("Dataset_Series", schema=None) as batch_op:
        batch_op.create_foreign_key(
            None, "Series", ["series_orthanc_id"], ["series_orthanc_id"]
        )
        batch_op.create_foreign_key(
            None, "Study", ["study_orthanc_id"], ["study_orthanc_id"]
        )

    with op.batch_alter_table("Dataset_Studies", schema=None) as batch_op:
        batch_op.create_foreign_key(
            None, "Study", ["study_orthanc_id"], ["study_orthanc_id"]
        )

    # 重新启用所有约束
    op.execute("SET CONSTRAINTS ALL IMMEDIATE")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Patient', schema=None) as batch_op:
        batch_op.drop_column('patient_weight')

    with op.batch_alter_table('Dataset_Studies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('Dataset_Series', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
