"""empty message

Revision ID: c45cd04799aa
Revises: 8eb98de59e6e
Create Date: 2024-02-29 18:13:53.814798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45cd04799aa'
down_revision = '8eb98de59e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acc_group')
    op.drop_table('dataset_group')
    with op.batch_alter_table('Acc_Group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_upload_dataset', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Acc_Group', schema=None) as batch_op:
        batch_op.drop_column('can_upload_dataset')
        batch_op.drop_column('editable')

    op.create_table('dataset_group',
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('editable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['Dataset.id'], name='dataset_group_dataset_id_fkey'),
    sa.ForeignKeyConstraint(['group_id'], ['Group.id'], name='dataset_group_group_id_fkey')
    )
    op.create_table('acc_group',
    sa.Column('acc_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('editable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_upload_dataset', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('owner', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['acc_id'], ['Account.id'], name='acc_group_acc_id_fkey'),
    sa.ForeignKeyConstraint(['group_id'], ['Group.id'], name='acc_group_group_id_fkey')
    )
    # ### end Alembic commands ###
