"""empty message

Revision ID: f353221143ae
Revises: 79fd02cf9e0d
Create Date: 2024-02-29 21:27:28.563191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f353221143ae'
down_revision = '79fd02cf9e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Group', schema=None) as batch_op:
        batch_op.drop_column('valid')

    # ### end Alembic commands ###
